name: Update flag ids

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  update_db:
    runs-on: ubuntu-latest

    permissions:
        contents: write
        pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements_dev.txt

      - name: Update FLAG IDs
        run: |
          python script/update_db.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: db_update
          commit-message: "[skip ci] Update flag ids."
          title: Update flag ids
          body: Automated FLAG ID database update from https://www.dlms.com/flag-id-directory/ by DLMS UA.
